(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){
(function() {

  var onScroll = function(e) {
    if ($.active != 0) return;

    if (e.data) {
      var offset = e.data.offset;
    };

    if (offset === undefined) {
      offset = $(window).height() * 0.7;
    }
    var viewPortBottom = $(window).scrollTop() + $(window).height(),
      breakPoint = $(document).height() - offset;
      reachedBottom = viewPortBottom >= breakPoint;

    if (!reachedBottom) return;
    $(window).trigger('infiniteScroll');
  };

  $.onInfiniteScroll = function(callback, options) {
    $(window).on('infiniteScroll', callback);
    $(window).on('scroll.infinite', options, onScroll);
  };

  $.destroyInfiniteScroll = function() {
    $(window).off('infiniteScroll');
    $(window).off('scroll.infinite');
  };

})();

},{}],2:[function(require,module,exports){
// Generated by CoffeeScript 1.4.0
(function() {
  var RawBirds, placeBird, placePseudoBird;

  RawBirds = [
    {
      "bid": "amsel",
      "de_name": "Amsel",
      "en_name": "Common blackbird"
    }, {
      "bid": "ara",
      "de_name": "Ara",
      "en_name": "Ara"
    }, {
      "bid": "bachstelze",
      "de_name": "Bachstelze",
      "en_name": "White wagtail"
    }, {
      "bid": "blaumeise",
      "de_name": "Blaumeise",
      "en_name": "Eurasian blue tit"
    }, {
      "bid": "buchfink",
      "de_name": "Buchfink",
      "en_name": "Common chaffinch"
    }, {
      "bid": "buntspecht",
      "de_name": "Buntspecht",
      "en_name": "Great spotted woodpecker"
    }, {
      "bid": "stieglitz",
      "de_name": "Distelfink",
      "en_name": "European goldfinch"
    }, {
      "bid": "dohle",
      "de_name": "Dohle",
      "en_name": "Western jackdaw"
    }, {
      "bid": "eichelhaeher",
      "de_name": "Eichelh\u00e4her",
      "en_name": "Eurasian jay"
    }, {
      "bid": "elster",
      "de_name": "Elster",
      "en_name": "Eurasian magpie"
    }, {
      "bid": "feldsperling",
      "de_name": "Feldsperling",
      "en_name": "Eurasian tree sparrow"
    }, {
      "bid": "fitis",
      "de_name": "Fitis",
      "en_name": "Willow warbler"
    }, {
      "bid": "gartenbaumlaeufer",
      "de_name": "Gartenbauml\u00e4ufer",
      "en_name": "Short-toed treecreeper"
    }, {
      "bid": "gartengrasmuecke",
      "de_name": "Gartengrasm\u00fccke",
      "en_name": "Garden warbler"
    }, {
      "bid": "gartenrotschwanz",
      "de_name": "Gartenrotschwanz",
      "en_name": "Common redstart"
    }, {
      "bid": "gimpel",
      "de_name": "Gimpel",
      "en_name": "Eurasian bullfinch"
    }, {
      "bid": "girlitz",
      "de_name": "Girlitz",
      "en_name": "European serin"
    }, {
      "bid": "goldammer",
      "de_name": "Goldammer",
      "en_name": "Yellowhammer"
    }, {
      "bid": "grauschnaepper",
      "de_name": "Grauschn\u00e4pper",
      "en_name": "spotted flycatcher"
    }, {
      "bid": "gruenfink",
      "de_name": "Gr\u00fcnfink",
      "en_name": "European greenfinch"
    }, {
      "bid": "hausrotschwanz",
      "de_name": "Hausrotschwanz",
      "en_name": "Black Redstart"
    }, {
      "bid": "haussperling",
      "de_name": "Haussperling",
      "en_name": "House sparrow"
    }, {
      "bid": "heckenbraunelle",
      "de_name": "Heckenbraunelle",
      "en_name": "Dunnock"
    }, {
      "bid": "kiwi",
      "de_name": "Kiwi",
      "en_name": "Kiwi"
    }, {
      "bid": "klappergrasmuecke",
      "de_name": "Klappergrasm\u00fccke",
      "en_name": "Lesser whitethroat"
    }, {
      "bid": "kleiber",
      "de_name": "Kleiber",
      "en_name": "Eurasian nuthatch"
    }, {
      "bid": "kohlmeise",
      "de_name": "Kohlmeise",
      "en_name": "Great tit"
    }, {
      "bid": "mauersegler",
      "de_name": "Mauersegler",
      "en_name": "Common swift"
    }, {
      "bid": "mehlschwalbe",
      "de_name": "Mehlschwalbe",
      "en_name": "Common house martin"
    }, {
      "bid": "moenchsgrasmuecke",
      "de_name": "M\u00f6nchsgrasm\u00fccke",
      "en_name": "Eurasian blackcap"
    }, {
      "bid": "rabenkraehe",
      "de_name": "Rabenkr\u00e4he",
      "en_name": "Carrion crow"
    }, {
      "bid": "rauchschwalbe",
      "de_name": "Rauchschwalbe",
      "en_name": "Barn swallow"
    }, {
      "bid": "ringeltaube",
      "de_name": "Ringeltaube",
      "en_name": "Common wood pigeon"
    }, {
      "bid": "rotkehlchen",
      "de_name": "Rotkehlchen",
      "en_name": "European robin"
    }, {
      "bid": "saatkraehe",
      "de_name": "Saatkr\u00e4he",
      "en_name": "Rook"
    }, {
      "bid": "schneeeule",
      "de_name": "Schneeeule",
      "en_name": "Snowy owl"
    }, {
      "bid": "schwanzmeise",
      "de_name": "Schwanzmeise",
      "en_name": "Long-tailed bushtit"
    }, {
      "bid": "singdrossel",
      "de_name": "Singdrossel",
      "en_name": "Song thrush"
    }, {
      "bid": "star",
      "de_name": "Star",
      "en_name": "Common starling"
    }, {
      "bid": "tannenmeise",
      "de_name": "Tannenmeise",
      "en_name": "Coal tit"
    }, {
      "bid": "tukan",
      "de_name": "Tukan",
      "en_name": "Toucan"
    }, {
      "bid": "tuerkentaube",
      "de_name": "T\u00fcrkentaube",
      "en_name": "Eurasian collared dove"
    }, {
      "bid": "weisskopfseeadler",
      "de_name": "Wei\u00dfkopfseeadler",
      "en_name": "Bald eagle"
    }, {
      "bid": "zaunkoenig",
      "de_name": "Zaunk\u00f6nig",
      "en_name": "Eurasian wren"
    }, {
      "bid": "zilpzalp",
      "de_name": "Zilpzalp",
      "en_name": "Common chiffchaff"
    }
  ];

  require('../ext/node_modules/jquery-on-infinite-scroll');

  /*
  	<!-- &url=https%3A%2F%2FHouseOfTweets.github.io -->
  
  		<div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 text-center">
  			<a href="https://twitter.com/intent/tweet?text=Ara&button_hashtag=HouseOfTweets">
  				<!-- &url=https%3A%2F%2FHouseOfTweets.github.io -->
  				<img src="https://placekitten.com/200/150" alt="Ara" />
  				<span>Tweet #HouseOfTweets</span>
  			</a>
  		</div>
  */


  placeBird = function(name, bid) {
    var a_tag, div_tag, img_tag, name_for_href, span_tag;
    console.log("Loadin' moar");
    img_tag = $("<img src=\"imgs/flag_de.png?" + bid + "\" alt=\"" + name + "\" width=\"200\" height=\"150\">");
    span_tag = $("<span>");
    span_tag.text("" + name + " #HouseOfTweets");
    a_tag = $("<a>");
    name_for_href = encodeURIComponent(name);
    a_tag.attr("href", "https://twitter.com/intent/tweet?text=" + name_for_href + "&button_hashtag=HouseOfTweets");
    a_tag.append(img_tag);
    a_tag.append(span_tag);
    div_tag = $('<div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 text-center">');
    div_tag.append(a_tag);
    return $("#hot-birdslist").append(div_tag);
  };

  placePseudoBird = function() {
    return placeBird("Weißkopfseeländer", "argh");
  };

  $.onInfiniteScroll(placePseudoBird, {
    offset: 202 + 20
  });

}).call(this);

},{"../ext/node_modules/jquery-on-infinite-scroll":1}]},{},[2]);
