(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){
(function() {

  var onScroll = function(e) {
    if ($.active != 0) return;

    if (e.data) {
      var offset = e.data.offset;
    };

    if (offset === undefined) {
      offset = $(window).height() * 0.7;
    }
    var viewPortBottom = $(window).scrollTop() + $(window).height(),
      breakPoint = $(document).height() - offset;
      reachedBottom = viewPortBottom >= breakPoint;

    if (!reachedBottom) return;
    $(window).trigger('infiniteScroll');
  };

  $.onInfiniteScroll = function(callback, options) {
    $(window).on('infiniteScroll', callback);
    $(window).on('scroll.infinite', options, onScroll);
  };

  $.destroyInfiniteScroll = function() {
    $(window).off('infiniteScroll');
    $(window).off('scroll.infinite');
  };

})();

},{}],2:[function(require,module,exports){
// Generated by CoffeeScript 1.11.1
(function() {
  var BirdFeeder, RawBirds_de, RawBirds_en, bird_template;

  RawBirds_de = [["elster", "Elster", "Elster"], ["feldsperling", "Feldsperling", "Feldsperling"], ["fitis", "Fitis", "Fitis"], ["gartenbaumlaeufer", "Gartenbauml\u00e4ufer", "Gartenbauml\u00e4ufer"], ["gartengrasmuecke", "Gartengrasm\u00fccke", "Gartengrasm\u00fccke"], ["gartenrotschwanz", "Gartenrotschwanz", "Gartenrotschwanz"], ["gimpel", "Gimpel", "Gimpel"], ["girlitz", "Girlitz", "Girlitz"], ["goldammer", "Goldammer", "Goldammer"], ["grauschnaepper", "Grauschn\u00e4pper", "Grauschn\u00e4pper"], ["gruenfink", "Gr\u00fcnfink", "Gr\u00fcnfink"], ["hausrotschwanz", "Hausrotschwanz", "Hausrotschwanz"], ["haussperling", "Haussperling", "Haussperling"], ["heckenbraunelle", "Heckenbraunelle", "Heckenbraunelle"], ["kiwi", "Kiwi", "Kiwi"], ["klappergrasmuecke", "Klappergrasm\u00fccke", "Klappergrasm\u00fccke"], ["kleiber", "Kleiber", "Kleiber"], ["kohlmeise", "Kohlmeise", "Kohlmeise"], ["mauersegler", "Mauersegler", "Mauersegler"], ["mehlschwalbe", "Mehlschwalbe", "Mehlschwalbe"], ["moenchsgrasmuecke", "M\u00f6nchsgrasm\u00fccke", "M\u00f6nchsgrasm\u00fccke"], ["rabenkraehe", "Rabenkr\u00e4he", "Rabenkr\u00e4he"], ["rauchschwalbe", "Rauchschwalbe", "Rauchschwalbe"], ["ringeltaube", "Ringeltaube", "Ringeltaube"], ["rotkehlchen", "Rotkehlchen", "Rotkehlchen"], ["saatkraehe", "Saatkr\u00e4he", "Saatkr\u00e4he"], ["schneeeule", "Schneeeule", "Schneeeule"], ["schwanzmeise", "Schwanzmeise", "Schwanzmeise"], ["singdrossel", "Singdrossel", "Singdrossel"], ["star", "Star", "Star"], ["tannenmeise", "Tannenmeise", "Tannenmeise"], ["tukan", "Tukan", "Tukan"], ["tuerkentaube", "T\u00fcrkentaube", "T\u00fcrkentaube"], ["weisskopfseeadler", "Wei\u00dfkopfseeadler", "Wei\u00dfkopfseeadler"], ["zaunkoenig", "Zaunk\u00f6nig", "Zaunk\u00f6nig"], ["zilpzalp", "Zilpzalp", "Zilpzalp"]];

  RawBirds_en = [["mehlschwalbe", "Common house martin", "Mehlschwalbe"], ["gartenrotschwanz", "Common redstart", "Gartenrotschwanz"], ["star", "Common starling", "Star"], ["mauersegler", "Common swift", "Mauersegler"], ["ringeltaube", "Common wood pigeon", "Ringeltaube"], ["heckenbraunelle", "Dunnock", "Heckenbraunelle"], ["moenchsgrasmuecke", "Eurasian blackcap", "M\u00f6nchsgrasm\u00fccke"], ["blaumeise", "Eurasian blue tit", "Blaumeise"], ["gimpel", "Eurasian bullfinch", "Gimpel"], ["tuerkentaube", "Eurasian collared dove", "T\u00fcrkentaube"], ["eichelhaeher", "Eurasian jay", "Eichelh\u00e4her"], ["elster", "Eurasian magpie", "Elster"], ["kleiber", "Eurasian nuthatch", "Kleiber"], ["feldsperling", "Eurasian tree sparrow", "Feldsperling"], ["zaunkoenig", "Eurasian wren", "Zaunk\u00f6nig"], ["stieglitz", "European goldfinch", "Distelfink"], ["gruenfink", "European greenfinch", "Gr\u00fcnfink"], ["rotkehlchen", "European robin", "Rotkehlchen"], ["girlitz", "European serin", "Girlitz"], ["gartengrasmuecke", "Garden warbler", "Gartengrasm\u00fccke"], ["kohlmeise", "Great tit", "Kohlmeise"], ["haussperling", "House sparrow", "Haussperling"], ["kiwi", "Kiwi", "Kiwi"], ["klappergrasmuecke", "Lesser whitethroat", "Klappergrasm\u00fccke"], ["schwanzmeise", "Long-tailed bushtit", "Schwanzmeise"], ["saatkraehe", "Rook", "Saatkr\u00e4he"], ["gartenbaumlaeufer", "Short-toed treecreeper", "Gartenbauml\u00e4ufer"], ["schneeeule", "Snowy owl", "Schneeeule"], ["singdrossel", "Song thrush", "Singdrossel"], ["buntspecht", "Spotted woodpecker", "Buntspecht"], ["tukan", "Toucan", "Tukan"], ["dohle", "Western jackdaw", "Dohle"], ["bachstelze", "White wagtail", "Bachstelze"], ["fitis", "Willow warbler", "Fitis"], ["goldammer", "Yellowhammer", "Goldammer"], ["grauschnaepper", "spotted flycatcher", "Grauschn\u00e4pper"]];

  bird_template = function(bid, display, tweet) {
    return "<div class=\"col-xs-12 col-sm-6 col-md-4 col-lg-3 text-center\">\n  <div class=\"bird-entry\">\n    <div class=\"bird-image\">\n      <img src=\"imgs/" + bid + ".jpg\" alt=\"" + display + "\"/>\n    </div>\n    <div class=\"caption\">\n      <span class=\"caption-text\">" + display + "</span>\n      <a class=\"tw-widget\" href=\"https://twitter.com/intent/tweet?text=" + tweet + "&button_hashtag=HouseOfTweets\">\n        <span class=\"tw-img\"></span>\n        <span class=\"tw-label\"> Tweet </span>\n      </a>\n    </div>\n  </div>\n</div>";
  };

  require('../ext/node_modules/jquery-on-infinite-scroll');

  BirdFeeder = {
    birds: null,
    nextBirdIdx: 0,
    init: function() {
      var i, lang, lang_tag, lang_tags, results;
      console.log("Auto-detect language");
      lang_tags = $("ul.navbar-right > li.active img");
      lang_tag = $(lang_tags[0]);
      lang = lang_tag.attr("alt");
      this.birds = {
        "Deutsch": RawBirds_de,
        "English": RawBirds_en
      }[lang];
      $.onInfiniteScroll((function() {
        return BirdFeeder.push();
      }), {
        offset: 397 + 20
      });
      results = [];
      for (i = 1; i <= 4; i++) {
        results.push($(window).trigger('scroll.infinite'));
      }
      return results;
    },
    placeBird: function(bid, display, tweet) {
      var div_tag;
      console.log("Loadin' moar");
      div_tag = $(bird_template(bid, display, tweet));
      return $("#hot-birdslist").append(div_tag);
    },
    push: function() {
      var bid, display, i, ref, results, tweet;
      if (this.nextBirdIdx < this.birds.length) {
        ref = this.birds[this.nextBirdIdx], bid = ref[0], display = ref[1], tweet = ref[2];
        console.log(this.birds[this.nextBirdIdx]);
        this.nextBirdIdx += 1;
        BirdFeeder.placeBird(bid, display, tweet);
        results = [];
        for (i = 1; i <= 4; i++) {
          results.push($(window).trigger('scroll.infinite'));
        }
        return results;
      } else {
        $("#hot-load-gif").remove();
        return $.destroyInfiniteScroll();
      }
    }
  };

  BirdFeeder.init();

}).call(this);

},{"../ext/node_modules/jquery-on-infinite-scroll":1}]},{},[2]);
