(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){
(function() {

  var onScroll = function(e) {
    if ($.active != 0) return;

    if (e.data) {
      var offset = e.data.offset;
    };

    if (offset === undefined) {
      offset = $(window).height() * 0.7;
    }
    var viewPortBottom = $(window).scrollTop() + $(window).height(),
      breakPoint = $(document).height() - offset;
      reachedBottom = viewPortBottom >= breakPoint;

    if (!reachedBottom) return;
    $(window).trigger('infiniteScroll');
  };

  $.onInfiniteScroll = function(callback, options) {
    $(window).on('infiniteScroll', callback);
    $(window).on('scroll.infinite', options, onScroll);
  };

  $.destroyInfiniteScroll = function() {
    $(window).off('infiniteScroll');
    $(window).off('scroll.infinite');
  };

})();

},{}],2:[function(require,module,exports){
// Generated by CoffeeScript 1.10.0
(function() {
  var BirdFeeder, RawBirds_de, RawBirds_en, placeBird;

  RawBirds_de = [["elster", "Elster"], ["feldsperling", "Feldsperling"], ["fitis", "Fitis"], ["gartenbaumlaeufer", "Gartenbauml\u00e4ufer"], ["gartengrasmuecke", "Gartengrasm\u00fccke"], ["gartenrotschwanz", "Gartenrotschwanz"], ["gimpel", "Gimpel"], ["girlitz", "Girlitz"], ["goldammer", "Goldammer"], ["grauschnaepper", "Grauschn\u00e4pper"], ["gruenfink", "Gr\u00fcnfink"], ["hausrotschwanz", "Hausrotschwanz"], ["haussperling", "Haussperling"], ["heckenbraunelle", "Heckenbraunelle"], ["kiwi", "Kiwi"], ["klappergrasmuecke", "Klappergrasm\u00fccke"], ["kleiber", "Kleiber"], ["kohlmeise", "Kohlmeise"], ["mauersegler", "Mauersegler"], ["mehlschwalbe", "Mehlschwalbe"], ["moenchsgrasmuecke", "M\u00f6nchsgrasm\u00fccke"], ["rabenkraehe", "Rabenkr\u00e4he"], ["rauchschwalbe", "Rauchschwalbe"], ["ringeltaube", "Ringeltaube"], ["rotkehlchen", "Rotkehlchen"], ["saatkraehe", "Saatkr\u00e4he"], ["schneeeule", "Schneeeule"], ["schwanzmeise", "Schwanzmeise"], ["singdrossel", "Singdrossel"], ["star", "Star"], ["tannenmeise", "Tannenmeise"], ["tukan", "Tukan"], ["tuerkentaube", "T\u00fcrkentaube"], ["weisskopfseeadler", "Wei\u00dfkopfseeadler"], ["zaunkoenig", "Zaunk\u00f6nig"], ["zilpzalp", "Zilpzalp"]];

  RawBirds_en = [["mehlschwalbe", "Common house martin"], ["gartenrotschwanz", "Common redstart"], ["star", "Common starling"], ["mauersegler", "Common swift"], ["ringeltaube", "Common wood pigeon"], ["heckenbraunelle", "Dunnock"], ["moenchsgrasmuecke", "Eurasian blackcap"], ["blaumeise", "Eurasian blue tit"], ["gimpel", "Eurasian bullfinch"], ["tuerkentaube", "Eurasian collared dove"], ["eichelhaeher", "Eurasian jay"], ["elster", "Eurasian magpie"], ["kleiber", "Eurasian nuthatch"], ["feldsperling", "Eurasian tree sparrow"], ["zaunkoenig", "Eurasian wren"], ["stieglitz", "European goldfinch"], ["gruenfink", "European greenfinch"], ["rotkehlchen", "European robin"], ["girlitz", "European serin"], ["gartengrasmuecke", "Garden warbler"], ["kohlmeise", "Great tit"], ["haussperling", "House sparrow"], ["kiwi", "Kiwi"], ["klappergrasmuecke", "Lesser whitethroat"], ["schwanzmeise", "Long-tailed bushtit"], ["saatkraehe", "Rook"], ["gartenbaumlaeufer", "Short-toed treecreeper"], ["schneeeule", "Snowy owl"], ["singdrossel", "Song thrush"], ["buntspecht", "Spotted woodpecker"], ["tukan", "Toucan"], ["dohle", "Western jackdaw"], ["bachstelze", "White wagtail"], ["fitis", "Willow warbler"], ["goldammer", "Yellowhammer"], ["grauschnaepper", "spotted flycatcher"]];

  require('../ext/node_modules/jquery-on-infinite-scroll');


  /*
  	<!-- &url=https%3A%2F%2FHouseOfTweets.github.io -->
  
  		<div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 text-center">
  			<a href="https://twitter.com/intent/tweet?text=#{name}&button_hashtag=HouseOfTweets">
  				<img src="imgs/#{bid}.jpg" alt="#{name}" width="200" height="150">
  				<p>#{name} #HouseOfTweets</p>
  			</a>
  		</div>
   */

  placeBird = function(name, bid) {
    var a_tag, div_tag, img_tag, name_for_href, p_tag;
    console.log("Loadin' moar");
    img_tag = $("<img src=\"imgs/" + bid + ".jpg\" alt=\"" + name + "\" width=\"200\" height=\"150\">");
    p_tag = $("<p class=\"custom-bird-caption\">");
    p_tag.text(name + " #HouseOfTweets");
    a_tag = $("<a>");
    name_for_href = encodeURIComponent(name);
    a_tag.attr("href", "https://twitter.com/intent/tweet?text=" + name_for_href + "&button_hashtag=HouseOfTweets");
    a_tag.append(img_tag);
    a_tag.append(p_tag);
    div_tag = $('<div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 text-center">');
    div_tag.append(a_tag);
    return $("#hot-birdslist").append(div_tag);
  };

  BirdFeeder = {
    birds: null,
    nextBirdIdx: 0,
    init: function() {
      var lang, lang_tag, lang_tags;
      console.log("Auto-detect language");
      lang_tags = $("ul.navbar-right > li.active img");
      lang_tag = $(lang_tags[0]);
      lang = lang_tag.attr("alt");
      this.birds = {
        "Deutsch": RawBirds_de,
        "English": RawBirds_en
      }[lang];
      return $.onInfiniteScroll((function() {
        return BirdFeeder.push();
      }), {
        offset: 202 + 20
      });
    },
    push: function() {
      var bid, name, ref;
      if (this.nextBirdIdx < this.birds.length) {
        ref = this.birds[this.nextBirdIdx], bid = ref[0], name = ref[1];
        this.nextBirdIdx += 1;
        return placeBird(name, bid);
      } else {
        return $.destroyInfiniteScroll();
      }
    }
  };

  BirdFeeder.init();

}).call(this);

},{"../ext/node_modules/jquery-on-infinite-scroll":1}]},{},[2]);
